name: FACT
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=21.3.1
  - pip:
    - numpy==1.19.5
    - opencv-contrib-python==3.4.2.17
    - matplotlib==3.3.4
    - jupyter==1.0.0
    - scikit-learn==0.23.0
    - scipy==1.5.4
    - torch==1.8.0        
    - torchvision==0.9.0  
    - tqdm==4.59.0        
    - pandas==1.2.3       
    - transformers==4.30.2 
    - pillow==8.1.0       
    - opencv-python-headless==4.5.1.48 
    - pytorchtools==0.0.2 
    - sentencepiece==0.1.99
